# Generated by Django 5.1.1 on 2024-09-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList', '0002_remove_todoitem_title_todoitem_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='title',
            field=models.CharField(default='Untitled', max_length=100),
        ),
    ]
